# Maximum Discord upload size, about 8MB
DISCORD_MAX_SIZE = 7.9e6

# Star emoji
STAR = '\N{WHITE MEDIUM STAR}'

# Colour used for the bot's own role
SELF_COLOUR = 0xbe03fd

# Colour used when creating user roles
DEFAULT_ROLE_COLOUR = 0x0165fc

# Default datetime formatting
TIME_FORMAT = '%H:%M - %d.%m.%y'

# Char to Unicode dict
EMOJI_DICT = {
    "a": "\N{REGIONAL INDICATOR SYMBOL LETTER A}",
    "b": "\N{REGIONAL INDICATOR SYMBOL LETTER B}",
    "c": "\N{REGIONAL INDICATOR SYMBOL LETTER C}",
    "d": "\N{REGIONAL INDICATOR SYMBOL LETTER D}",
    "e": "\N{REGIONAL INDICATOR SYMBOL LETTER E}",
    "f": "\N{REGIONAL INDICATOR SYMBOL LETTER F}",
    "g": "\N{REGIONAL INDICATOR SYMBOL LETTER G}",
    "h": "\N{REGIONAL INDICATOR SYMBOL LETTER H}",
    "i": "\N{REGIONAL INDICATOR SYMBOL LETTER I}",
    "j": "\N{REGIONAL INDICATOR SYMBOL LETTER J}",
    "k": "\N{REGIONAL INDICATOR SYMBOL LETTER K}",
    "l": "\N{REGIONAL INDICATOR SYMBOL LETTER L}",
    "m": "\N{REGIONAL INDICATOR SYMBOL LETTER M}",
    "n": "\N{REGIONAL INDICATOR SYMBOL LETTER N}",
    "o": "\N{REGIONAL INDICATOR SYMBOL LETTER O}",
    "p": "\N{REGIONAL INDICATOR SYMBOL LETTER P}",
    "q": "\N{REGIONAL INDICATOR SYMBOL LETTER Q}",
    "r": "\N{REGIONAL INDICATOR SYMBOL LETTER R}",
    "s": "\N{REGIONAL INDICATOR SYMBOL LETTER S}",
    "t": "\N{REGIONAL INDICATOR SYMBOL LETTER T}",
    "u": "\N{REGIONAL INDICATOR SYMBOL LETTER U}",
    "v": "\N{REGIONAL INDICATOR SYMBOL LETTER V}",
    "w": "\N{REGIONAL INDICATOR SYMBOL LETTER W}",
    "x": "\N{REGIONAL INDICATOR SYMBOL LETTER X}",
    "y": "\N{REGIONAL INDICATOR SYMBOL LETTER Y}",
    "z": "\N{REGIONAL INDICATOR SYMBOL LETTER Z}",
    "!": "\N{HEAVY EXCLAMATION MARK SYMBOL}",
    "?": "\N{BLACK QUESTION MARK ORNAMENT}",
    "0": "0\u20e3",
    "1": "1\u20e3",
    "2": "2\u20e3",
    "3": "3\u20e3",
    "4": "4\u20e3",
    "5": "5\u20e3",
    "6": "6\u20e3",
    "7": "7\u20e3",
    "8": "8\u20e3",
    "9": "9\u20e3"
}
